RECIPES = [
    {
        "id": 1,
        "label": "Chicken Vesuvio",
        "source": "Serious Eats",
        "url": "http://www.seriouseats.com/recipes/2011/12/chicken-vesuvio-recipe.html",
        "date": "2011-05-12",
        "user_id": 1,
        "is_public": True,
    },
    {
        "id": 2,
        "label": "Chicken Paprikash",
        "source": "No Recipes",
        "url": "http://norecipes.com/recipe/chicken-paprikash/",
        "date": "2013-07-19",
        "user_id": 2,
        "is_public": True,
    },
    {
        "id": 3,
        "label": "Cauliflower and Tofu Curry Recipe",
        "source": "Serious Eats",
        "url": "http://www.seriouseats.com/recipes/2011/02/cauliflower-and-tofu-curry-recipe.html",
        "date": "2015-09-23",
        "user_id": 3,
        "is_public": True,
    },
    {
        "id": 4,
        "label": "Spaghetti Carbonara",
        "source": "Simply Recipes",
        "url": "https://www.simplyrecipes.com/recipes/spaghetti_carbonara/",
        "date": "2017-11-30",
        "user_id": 4,
        "is_public": False,
    },
    {
        "id": 5,
        "label": "Classic Beef Stroganoff",
        "source": "The Spruce Eats",
        "url": "https://www.thespruceeats.com/classic-beef-stroganoff-recipe-4807477",
        "date": "2019-02-14",
        "user_id": 5,
        "is_public": False,
    },
    {
        "id": 6,
        "label": "Vegetarian Chili",
        "source": "Cookie and Kate",
        "url": "https://cookieandkate.com/vegetarian-chili-recipe/",
        "date": "2020-06-21",
        "user_id": 6,
        "is_public": True,
    },
    {
        "id": 7,
        "label": "Eggplant Parmesan",
        "source": "Bon Appétit",
        "url": "https://www.bonappetit.com/recipe/classic-eggplant-parmesan",
        "date": "2021-08-05",
        "user_id": 7,
        "is_public": False,
    },
    {
        "id": 8,
        "label": "Thai Green Curry",
        "source": "BBC Good Food",
        "url": "https://www.bbcgoodfood.com/recipes/thai-green-curry",
        "date": "2022-03-15",
        "user_id": 8,
        "is_public": False,
    },
    {
        "id": 9,
        "label": "French Onion Soup",
        "source": "The Kitchn",
        "url": "https://www.thekitchn.com/how-to-make-french-onion-soup-240508",
        "date": "2023-01-10",
        "user_id": 9,
        "is_public": True,
    },
    {
        "id": 10,
        "label": "Margarita Pizza",
        "source": "Serious Eats",
        "url": "https://www.seriouseats.com/margherita-pizza-recipe",
        "date": "2010-04-18",
        "user_id": 10,
        "is_public": True,
    },
    {
        "id": 11,
        "label": "Shrimp Scampi",
        "source": "Food Network",
        "url": "https://www.foodnetwork.com/recipes/shrimp-scampi-recipe",
        "date": "2012-12-25",
        "user_id": 11,
        "is_public": True,
    },
    {
        "id": 12,
        "label": "Pancakes",
        "source": "AllRecipes",
        "url": "https://www.allrecipes.com/recipe/21014/good-old-fashioned-pancakes/",
        "date": "2014-10-31",
        "user_id": 12,
        "is_public": False,
    },
    {
        "id": 13,
        "label": "Vegetable Stir Fry",
        "source": "Love and Lemons",
        "url": "https://www.loveandlemons.com/vegetable-stir-fry/",
        "date": "2016-07-04",
        "user_id": 13,
        "is_public": False,
    },
    {
        "id": 14,
        "label": "BBQ Pulled Pork",
        "source": "Gimme Some Oven",
        "url": "https://www.gimmesomeoven.com/bbq-pulled-pork/",
        "date": "2018-09-09",
        "user_id": 14,
        "is_public": True,
    },
    {
        "id": 15,
        "label": "Fish Tacos",
        "source": "Delish",
        "url": "https://www.delish.com/cooking/recipe-ideas/recipes/a53829/easy-fish-tacos-recipe/",
        "date": "2024-05-20",
        "user_id": 15,
        "is_public": False,
    },
]
